### ISSUE TITLE
changes with the padding in the menu 

### ISSUE THREAD

**Issue by pwrstudio** [pwrstudio/rr_wp#25]
![unnamed](https://cloud.githubusercontent.com/assets/8209990/18352221/cc9dfabe-75dd-11e6-9b04-6087175e755a.png)
![unnamed-1](https://cloud.githubusercontent.com/assets/8209990/18352222/ccbbcbc0-75dd-11e6-8df5-aacfb920e028.png)

**Comment by br092616** [comment]
great in firefox, would it be possible for safari and chrome to change it to this...? Only in the open menu it'd need to be changed also otherwise the active menu is moving a little
![screen shot 2016-09-11 at 7 57 06 pm](https://cloud.githubusercontent.com/assets/22127585/18419411/3c4d47f6-785a-11e6-8fc7-244ffaf185cd.png)
![screen shot 2016-09-11 at 7 57 52 pm](https://cloud.githubusercontent.com/assets/22127585/18419412/3c4fac76-785a-11e6-880d-0c53ab70e7b8.png)

**Comment by pwrstudio** [comment]
you mean change the bottom padding to 4px only on safari and chrome? I can not easily change that on specific browsers. But the padding should behave the same on firefox/chrome/safari?

I can of course change it to 4px on all browsers...

**Comment by br092616** [comment]
ok 4px on all thx
