### ISSUE TITLE
main menu

### ISSUE THREAD

**Issue by br092616** [pwrstudio/rr_wp#54]
edited the menu and added a new page, which seems to make "colophon" move to a next line. I assumed the menu-centering will adjust to whatever is in there. If thats too much let me know and I can ask Alejandro for a final edit of the menu and final menu-names, thanks!

**Comment by br092616** [comment]
assigning pages to the new (menu)page "Ways of Reading", not quite sure what's happening with the menu on the left hand side?

**Comment by manegame** [comment]
Best would be to have a set amount of menu items, because:

When it comes to a new page, the parent page file has to be made manually. This page loads all its child elements into the page. 
It seems like the page loaded the first parent available instead of the new page which did not exist yet.

The menu items are defined by a percentage value, which is added manually in the theme.
 
Adjusted and [online now](http://52.91.41.41/ways-of-reading/)

**Comment by pwrstudio** [comment]
I assumed the pages/sections/menu items in the sketch. adding more is not trivial, as there are so many exceptions and special cases with the layout/behaviour.

**Comment by br092616** [comment]
ok I understand, I wasn't aware of that. I already told Alejandro that they
won't be able to edit the main menu.

Not quite sure: will they be able to edit the menus on the left hand side?

thanks!

**Comment by br092616** [comment]
please add another extra rule, if possible: could "about" and "colophon" both have 24px padding on the outside?

**Comment by pwrstudio** [comment]
Yes, they can add sub-pages to the top-level pages, and then additional sub-sub-pages to those:

![screen shot 2016-09-20 at 4 02 47 pm](https://cloud.githubusercontent.com/assets/8209990/18662220/f2c73aa8-7f4b-11e6-924b-01d0c2d95d89.png)

To for example add new "guiding Questions" or Understandings.

And this will reflect in the left-hand menu.

**Comment by br092616** [comment]
great thx!
